### PR TITLE
chore: fix resources env vars

### PR DESCRIPTION
**Pull request by psegedy**
RHINENG-12322

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by psegedy** [comment]
same 25 failures as with resources stripped (--no-remove-resources vuln4shift-backend) which means that now the app can be deployed to ephemeral without any extra resource settings
@mtclinton could you take a look at these test failures, please?

**Review by MichaelMraka — APPROVED** [review]

**Pull request merged**
