### PR TITLE
Update dependencies to resolve vulnerabilities

### PR DESCRIPTION
**Pull request by michalslomczynski**
[RHINENG-2524]
[RHINENG-2533]
[RHINENG-2540]

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by michalslomczynski** [comment]
/retest

Failed: Failed to wait for vmaas sync - vuln4shift in time.

**Review by jdobes — APPROVED** [review]

**Pull request merged**
