### PR TITLE
chore: add sha-extractor as a dependency

### PR DESCRIPTION
**Pull request by juandspy**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by juandspy** [comment]
> Commits missing Jira IDs: [69cd053](https://github.com/RedHatInsights/vuln4shift-backend/commit/69cd05344a4f09afc0aa9bade1f478c2ed295a2f)

it's because `CCXDEV` is not part of the regex [here](https://github.com/tkasparek/gh-bot/blob/884f4628b4451b01d509fa309035bba57ee0d5d0/src/index.ts#L5)

**Comment by jdobes** [comment]
> > Commits missing Jira IDs: [69cd053](https://github.com/RedHatInsights/vuln4shift-backend/commit/69cd05344a4f09afc0aa9bade1f478c2ed295a2f)

> it's because CCXDEV is not part of the regex [here](https://github.com/tkasparek/gh-bot/blob/884f4628b4451b01d509fa309035bba57ee0d5d0/src/index.ts#L5)

https://github.com/RedHatInsights/jira-linking-gh-bot/commit/c5e0225e865d767f2e38e90b44d76e85f000655e

**Comment by juandspy** [comment]
now there are 3 tests failing but the sha-extractor is correctly deployed :). WDYT @jdobes ?

**Review by jdobes — APPROVED** [review]
These failing tests are not relevant to the sha-extractor. LGTM

**Pull request merged**
